const formData = {
  NameofApplicant: "John Doe",
  constitution: "Individual",
  profession1: "Software Developer",
  YearofEstablishment: "2010",
  Businessactivity: "Software Development and Consulting",
  Registerofficeaddress: "1234 Software St, Tech City",
  Addressforcommunication_office: "1234 Software St, Tech City",
  Addressforcommunication_work: "5678 Development Ave, Tech Park",
  Communicationdetails_landline: "123-456-7890",
  Communicationdetails_mobile: "098-765-4321",
  Communicationdetails_email: "contact@techcompany.com",
  Communicationdetails_web: "https://www.techcompany.com",
  Legalinfo_aadhar: "123456789101",
  Legalinfo_pancard: "ABCDE1234F",
  Legalinfo_GSTNo: "22AAAAA0000A1Z5",
  Legalinfo_CompanyFirmRegNo: "C12345678901234",
  Legalinfo_SocietyAssociationRegNo: "12345678901234",
  Personauthorized_Name: "Jane Doe",
  Personauthorized_Designation: "CTO",
  personauthorized_pan: "BCDEA1234G",
  personauthorized_aadhar: "432167890123",
  personauthorized_phone: "098-765-4321",
  personauthorized_email: "jane.doe@techcompany.com",
  Maincategory: "IT and Software",
  Subcategory: "Software Development",
  Cateringtomarket: "Global",
  Percentageofimports: "10%",
  Percentageofexports: "50%",
  Foreigncollaboration_country: "USA",
  Foreigncollaboration_collaborator: "GlobalTech Inc",
  Classificationofindustry: "Large",
  Annualturnover_year1: "10",
  Annualturnover_year2: "1200000",
  Annualturnover_year3: "150",
  Noofpersonsemployed_direct: "50",
  Noofpersonsemployed_works: "200",
  Noofpersonsemployed_indirect: "100",
  Noofpersonsemployed_outsourced: "30",
  ESIC: "Yes",
  EPF: "Yes",
  Detailsofbranches: "Tech City, Tech Park",
  Memberofanyother: "Yes",
  association_name: "Tech Industry Association",
  is_office_bearer: "No",
  association_position: "",
  reason_for_joining_chamber: "Networking and Business Opportunities",
  e_sign: null,
  IncomeandExpenditure: null,
  incometaxtpan: null,
  FactoryRegistrationCertificate: null,
  MemorandumArticleofAssociation: null,
  GSTINRegistrationCopy: null,
  IECodeCertificate: null,
  ProfessionalCertificate: null,
  CopyofLandDocument: null,
  LandHolding: null,
  passportsizephoto: null,
  DirectorsPartners: null,
  form_status: "pending",
  Reasonforrejection: "",
};

export default formData;
